### ISSUE TITLE
Unknown turnip stalk market pattern

### ISSUE THREAD

**Issue by evansantos** [drfuzzyness/google-sheets-stalk-market-calculator#1]
Hi, first of all nice tool you are offering  :+1:, but might not be covering all cases

After I inserted all my possible selling prices, it gave error saying that the pattern wasn't found, but I have to fake the Mae's turnip sell price to make it work, which gave me small spike but I think is possibly another pattern.

I'm adding the values inputed below:

the actual prices that I have are

|                      | AM  | PM  |
|----------------------|-----|-----|
| Sunday \(Buy Price\) | 107 |     |
| Monday               | 39  | 35  |
| Tuesday              | 31  | 27  |
| Wednesday            | 22  | 18  |
| Thursday             | 14  | 111 |
| Friday               | 93  | 153 |
| Saturday             |     |     |

Faked prices to show correctly:

|                      | AM  | PM  |
|----------------------|-----|-----|
| Sunday \(Buy Price\) | 97 |     |
| Monday               | 39  | 35  |
| Tuesday              | 31  | 27  |
| Wednesday            | 22  | 18  |
| Thursday             | 14  | 111 |
| Friday               | 93  | 153 |
| Saturday             |     |     |

I'll be watching the next two days and update here to see what kind and how we can fix it :)

**Comment by greatcloudninja** [comment]
I'm in the same boat. My purchase price on Sunday was 108, and everything was going fine for a small spike until this evening. Before putting in the PM price, it was generating a range of 97-152, but I came in at 93.
Screenshot of my current prices below:
![Screenshot_20200402-183118_Sheets](https://user-images.githubusercontent.com/63079356/78309288-2f32b400-7510-11ea-9a52-405f7d0d546b.jpg)

**Comment by evansantos** [comment]
@greatcloudninja it's weird, because I think some of the patterns are based on the New Leaf, so might be refactored or be aware of this issue

**Comment by greatcloudninja** [comment]
I think you're right. I used a different site in New Leaf (Kurt Boyer's Stalk Market Wizard) and when I plug my pricing into that site, it comes back as a "rollercoaster" (random) pattern.

Update: 
Friday AM price: 98 bells
Friday PM price: 143 bells
Saturday AM price: 182 bells

**Comment by evansantos** [comment]
mine in the end gave small spike because of it prices, but although as I guess yours but it not effectively solve the problems of find out which will be the future price :(

**Comment by deusatiam** [comment]
I have a similar issue. Sunday buy price was 108 bells, Mon AM was 63 and Mon PM is 87.

**Comment by drfuzzyness** [comment]
Alrighty, it looks like the [upstream predictions logic](https://github.com/mikebryant/ac-nh-turnip-prices/blob/master/js/predictions.js) has changed. I'll see about porting those changes back. It might also make sense to refactor the code into typescript like [Fugiman has](https://github.com/Fugiman/google-sheets-stalk-market-calculator).

**Comment by PierreLouisBertrand** [comment]
With my prices from this week, the tool didn't manages to get a matching pattern.
![ACNH_pattern_doesnt_match](https://user-images.githubusercontent.com/34208341/78704689-87045d00-790c-11ea-8683-c9a30b01a915.png)

**Comment by drfuzzyness** [comment]
Alright, after testing the upstream predictions logic, it looks like somehow these sets of numbers aren't predicted. I'll leave this open as this is still a problem, but work right now doesn't leave me with much time to delve into the problem.

If you find this problem for your numbers, you might want to check out the upstream version of the code which might give you results (it didn't for me as of today).

 https://turnipprophet.io/index.html

**Comment by PierreLouisBertrand** [comment]
I understood why it's doesn't work with my prices !
It's because it's the first week where I'm buying turnips...
My bad

**Comment by lonelyVoxel** [comment]
Hey all, I was referred to this thread from a Twitter comment. I'm posting my table from this week here in hopes an additional data point can help.
A few notes:
-I was busy Wednesday morning and ended up not checking the price. I'm not opposed to time travelling for completion's sake, though.
-Changing the Friday PM price to 212 made the the data agree with a known Small Spike pattern
-This was the first week turnips were available to me. {Unsure if relevant but I've seen people say the first week is different?}

![image](https://user-images.githubusercontent.com/47798467/79048601-45193680-7bec-11ea-85cd-d5020386d15e.png)

**Comment by floofyorange** [comment]
Date | AM | PM
-- | -- | --
Price on Sunday | 91 |  
Monday |   | 94
Tuesday | 88 | 84
Wednesday | 80 | 76
Thursday | 118 | 117
Friday | 181 | 185
Saturday | 163 | 44

Also first week turnips were available

**Comment by magicalgirlsammy** [comment]
I'm having the same error today.
My numbers so far have been:

Price on Sunday - 94
Monday AM - 100 
Monday PM - 153

**Comment by drfuzzyness** [comment]
Question for those with this problem, is this the first time **_you_** have bought turnips from **_your_** island's Daisy Mae?

If so, does removing (or setting to 0) your Sunday buy price give you results?

**Comment by magicalgirlsammy** [comment]
Yes I believe this is the first time buying turnips on my island, and setting the price to 0 and removing the price still turn up(lol) an error :(

**Comment by lonelyVoxel** [comment]
The sheet doesn't seem to work with zero in the Sunday box. My prices matched a Small Spike with the substitution of 110 for the initial price, however. 
![image](https://user-images.githubusercontent.com/47798467/79166211-b1de2d80-7db2-11ea-854b-5a8c93addbc0.png)

**Comment by drfuzzyness** [comment]
This may be resolved by the new `Engine.gs` from #6. However, it looks like the bug only affects the first week so I don't know if anyone will notice.
