### ISSUE TITLE
When duplicating first sheet "Turnips", the new copy does not function

### ISSUE THREAD

**Issue by greiss122** [drfuzzyness/google-sheets-stalk-market-calculator#8]
Hi,

Having an issue where if I duplicate the first sheet ("Turnips", not "Turnips from external sheet"), the copy does not calculate price patterns or etc. The original, Turnip sheet does work.

Thank you!!

![image](https://user-images.githubusercontent.com/6404738/84309996-cf5f1780-ab15-11ea-9702-eeadf63209cf.png)

**Comment by drfuzzyness** [comment]
Whops, the readme didn't explain this.

You need to rename your duplicate sheet `Turnips {your name here}`

**Comment by greiss122** [comment]
Perfect! Working now. Thanks for the quick response!
